### ISSUE TITLE
Update Reverse Proxy URL + Analytics server down

### ISSUE THREAD

**Issue by jabbany** [feefles/piazza-analytics#11]
My old ssl cert expired and I got a fancy new wildcard cert. With this the reverse proxy has been moved to its own server. There's no configuration necessary on the extension's side other than the change in URL

The new URL for the piazza analytics service is `https://reverse.cdn.moe/piazza/`.

Also, it seems that the source API server is down and not answering any requests. Can you check and maybe fix/restart it? Thx.

**Comment by feefles** [comment]
Yeah it seems that people keep pinging the server and screwing it up... :/ maybe it's time to limit who can access this.

**Comment by jabbany** [comment]
Well my proxy is on `192.249.57.113` for reference in case you want to do IP whitelisting etc.

**Comment by feefles** [comment]
I think that the proxy is adding an extra slash or something. 
192.249.57.113 - - [06/Jan/2016 20:50:40] "GET //tag_good/idj5lp6gixc6xn/2164 HTTP/1.0" 404 -
65.130.209.240 - - [06/Jan/2016 20:50:54] "GET /tag_good/idj5lp6gixc6xn/2164 HTTP/1.1" 200 -

The second is when I don't go through your proxy.

**Comment by jabbany** [comment]
Yeah, that's probably a config problem. I'm gonna look into it  later today.

**Comment by jabbany** [comment]
Fixed (I think)
Had an extra slash in the `proxy_pass` field for nginx.

**Comment by jabbany** [comment]
Closing ancient issue
